# Generated by Django 4.2.4 on 2023-09-06 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsettings',
            name='back_image',
            field=models.ImageField(null=True, upload_to='backgroundimage/'),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='logo',
            field=models.ImageField(default=None, max_length=200, null=True, upload_to='logo/'),
        ),
        migrations.AlterField(
            model_name='navigation',
            name='bannerimage',
            field=models.ImageField(null=True, upload_to='bannerimage/'),
        ),
        migrations.AlterField(
            model_name='navigation',
            name='slider_image',
            field=models.ImageField(null=True, upload_to='sliderimage/'),
        ),
    ]
