# Generated by Django 4.2.4 on 2023-09-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_alter_navigation_page_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsettings',
            name='Siteinstagramlink',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
