# Generated by Django 4.2.4 on 2023-09-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_alter_globalsettings_siteinstagramlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigation',
            name='page_type',
            field=models.CharField(blank=True, choices=[('Home', 'Home'), ('Mission/Vision', 'Mission/Vision'), ('Home/About', 'Home/About'), ('Group', 'Group'), ('Slider', 'Slider'), ('Service', 'Service'), ('Service_1', 'Service_1'), ('Step', 'Step'), ('Step_1', 'Step_1'), ('Contact', 'Contact'), ('Connectstaff', 'Connectstaff')], max_length=50, null=True),
        ),
    ]
