# Generated by Django 4.2.4 on 2023-09-07 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_alter_navigation_page_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hiring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('business', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
