# Generated by Django 4.2.4 on 2023-09-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0008_alter_navigation_page_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigation',
            name='page_type',
            field=models.CharField(blank=True, choices=[('Home', 'Home'), ('Mission/Vision', 'Mission/Vision'), ('Home/About', 'Home/About'), ('Group', 'Group'), ('Slider', 'Slider'), ('Service', 'Service'), ('Service_1', 'Service_1'), ('Step', 'Step'), ('Step_1', 'Step_1'), ('Contact', 'Contact'), ('Connectstaff', 'Connectstaff'), ('mass', 'mass'), ('Contact_1', 'Contact_1'), ('Contact_2', 'Contact_2'), ('Testimonial', 'Testimonial'), ('Testimonial_1', 'Testimonial_1'), ('mass_1', 'mass_1'), ('mass_2', 'mass_2'), ('mass_3', 'mass_3')], max_length=50, null=True),
        ),
    ]
